[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable processing
[build.processing]
  skip_processing = false

# Build command to replace environment variables
[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
